# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: cz_hyy6848
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# mybatis
mybatis:
  config: mybatis-config.xml
  type-aliases-package: com.hello.hellospring.dto
  mapper-locations: mybatis/mapper/*.xml

